name: Deploy AStore to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ZapStore Action
        uses: zapstore/action@master
        with:
          repository: allpeacein23-dotcom/AStore
          base_url: /AStore/
          # apps_dir: apps  # မင်းရဲ့ APK တွေထားတဲ့ folder နာမည်

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # ဒါက အရေးကြီးတယ်၊ build ထွက်လာတဲ့ folder ကိုပဲ တင်ရမယ်

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
